# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aplexica < Formula
  desc "Cross-agent state portability for AI coding agents (deterministic lossless replication)."
  homepage "https://aplexica.com"
  version "1.0.0"
  license "AGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Aplexica/Aplexica/releases/download/v1.0.0/aplexica-1.0.0-darwin-amd64.tar.gz"
      sha256 "f37a45ef0a0125bb380d2edc74c09ef95385ff50eb963f90a802ba730f439d55"

      define_method(:install) do
        bin.install "aplexica"
        bin.install "aplexica-status"
        bin.install "aplexicatray"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Aplexica/Aplexica/releases/download/v1.0.0/aplexica-1.0.0-darwin-arm64.tar.gz"
      sha256 "3c8c12f06519e3375f424909aece9ee04413e566cabe7d31ed15c1d17608ecda"

      define_method(:install) do
        bin.install "aplexica"
        bin.install "aplexica-status"
        bin.install "aplexicatray"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Aplexica/Aplexica/releases/download/v1.0.0/aplexica-1.0.0-linux-amd64.tar.gz"
      sha256 "fdb6cc64e99320c9a4ea6c6f2f128a64eed3f71a0a26eeef8b33b0915bd0e093"
      define_method(:install) do
        bin.install "aplexica"
        bin.install "aplexica-status"
        bin.install "aplexicatray"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Aplexica/Aplexica/releases/download/v1.0.0/aplexica-1.0.0-linux-arm64.tar.gz"
      sha256 "c2ec1ad0ffb931257d0a5c8115620385bb3cdec72ccc4597c9fde3c610131c60"
      define_method(:install) do
        bin.install "aplexica"
        bin.install "aplexica-status"
        bin.install "aplexicatray"
      end
    end
  end

  def caveats
    <<~EOS
      Aplexica installs aplexica (CLI + daemon), aplexica-status (tray status
      watcher helper), and aplexicatray (system-tray indicator).

      To complete setup:
        aplexica setup

      User data lives in ~/.aplexica/. Logs at ~/.aplexica/logs/.
      The daemon starts the local web UI and launches the tray when Aplexica runs.
      Local web UI: click the tray icon → Open Aplexica, or run `aplexica web open`.
    EOS
  end

  test do
    assert_match "v#{version}", shell_output("#{bin}/aplexica --version")
  end
end
